# Generated by Django 6.0.3 on 2026-04-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('PROCESS', 'In Process'), ('ACCEPTED', 'Accepted')], default='REPORTED', max_length=20),
        ),
    ]
